### ISSUE TITLE
cabal-install bootstrap error

### ISSUE THREAD

**Issue by izubkov** [yantonov/install-ghc#2]
Hi,
and thanks for the hard work.

I've stumbled against an error like this during manual installation on ubuntu:

> [14 of 42] Compiling Hackage.Security.TUF.Layout.Repo ( src/Hackage/Security/TUF/Layout/Repo.hs, dist/build/Hackage/Security/TUF/Layout/Repo.p_o )
> 
> src/Hackage/Security/TUF/Layout/Repo.hs:8:1: error:
>     Failed to load interface for ‘Distribution.Package’
>     Perhaps you haven't installed the profiling libraries for package ‘Cabal-1.24.0.0@Cabal-1.24.0.0-> > K3HaABmGH7AIWRS80LqYoH’?
>     Use -v to see a list of the files searched for.
> 
> src/Hackage/Security/TUF/Layout/Repo.hs:9:1: error:
>     Failed to load interface for ‘Distribution.Text’
>     Perhaps you haven't installed the profiling libraries for package ‘Cabal-1.24.0.0@Cabal-1.24.0.0-> > K3HaABmGH7AIWRS80LqYoH’?
>     Use -v to see a list of the files searched for.
> 
> Error during cabal-install bootstrap:
> Building the hackage-security package failed.

This should probably be addressed to cabal issues or so, but as a quick workaround one can replace
`DEFAULT_CONFIGURE_OPTS="--enable-library-profiling --enable-shared"` with `DEFAULT_CONFIGURE_OPTS="--enable-shared"` in cabal-install bootstrap.sh to disable profiling libraries.

**Comment by yantonov** [comment]
Hi! I have tried to reproduce issue and haven't find any issues. Sorry i cant have much time just now. Can you clarify ubuntu version, i try to reproduce issue at same environment.

**Comment by izubkov** [comment]
Sure,

> DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

**Comment by yantonov** [comment]
Thanks, it helps!
Solution:
install cabal with enable-library-support
Changes (install cabal section):
old: ./Setup configure --user
new: ./Setup configure --user --enable-library-profiling
Repository is already updated
(check latest commit [295a517cd7a5e6a1ada3780206a972ac14b828d0]).

**Comment by izubkov** [comment]
thanks! it works now

**Comment by yantonov** [comment]
Good news!)
